spring:
  application:
    name: helpdesk

  # DATABASE CONFIGURATION
  datasource:
    url: jdbc:mysql://localhost:3306/finalhelpdesk
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  # EMAIL CONFIGURATION
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8060

# JWT & REFRESH TOKEN CONFIGURATION
jwt:
  refresh-token-expiration: 604800000

# OTP CONFIGURATION
otp:
  expiration-minutes: 2
  max-attempts: 3