package com.example.helpdesk.enums;

public enum NotificationType {
    ASSIGNMENT_CONFIRMED,
    SLA_STARTED,
    SLA_WARNING,
    SLA_BREACH,
    TICKET_RESOLVED,
    TICKET_REOPENED,
    NEW_MESSAGE,
    ATTACHMENT_ADDED,
    TICKET_HOLD,
    TICKET_RESUMED,
    FEEDBACK_SUBMITTED,
    TICKET_CREATED,
    AGENT_ASSIGNED,
    MANAGER_ASSIGNED,
    STATUS_CHANGED,
    TICKET_ESCALATED,
    PRIORITY_CHANGED,
    CATEGORY_CHANGED,
    TICKET_REASSIGNED,
    TICKET_WITHDRAWN
}
