package com.example.helpdesk.enums;

public enum TicketEventType {
    TICKET_CREATED,
    ROUTING_PROPOSED,
    ASSIGNMENT_CONFIRMED,
    ASSIGNMENT_REJECTED,
    STATUS_CHANGED,
    PRIORITY_CHANGED,
    CATEGORY_CHANGED,
    MESSAGE_SENT,
    ATTACHMENT_ADDED,
    SLA_STARTED,
    SLA_WARNING,
    SLA_HOLD,
    SLA_RESUMED,
    SLA_MET,
    SLA_BREACHED,
    TICKET_RESOLVED,
    TICKET_REOPENED,
    FEEDBACK_SUBMITTED
}
